# Inc. 5000 Analysis

## Notebook 01 - Data Loading

### Objectives

- Import required libraries
- Load the cleaned Excel dataset
- Explore dataset structure
- Verify data types
- Display sample records
- Generate a quick overview

---

In [1]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)
pd.set_option("display.float_format", "{:,.2f}".format)

print("Libraries imported successfully.")

Libraries imported successfully.

## Load Dataset

In [3]:
# Path to dataset

file_path = r"C:\Users\dell\Desktop\Project\data\cleaned\inc5000_cleaned.xlsx"

df = pd.read_excel(file_path)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [4]:
df.head()

,id,rank,employee_count,company,state_name,state_code,city,metro,growth_percentage,revenue_usd,industry,years_on_list,revenue_per_employee,Revenue_in_million,company_size,employee_size_band,revenue_category,growth_category,rank_group,state region,efficiency_category
0,22890,1,227,Fuhu,California,CA,El Segundo,Los Angeles,"158,956.91",195640000,Consumer Products & Services,2,"861,850.22",195640000,Medium,Medium,Very High Revenue,Hyper Growth,Top 100,West,Excellent Efficiency
1,25747,2,191,Quest Nutrition,California,CA,El Segundo,Los Angeles,"57,347.92",82640563,Food & Beverage,1,"432,673.10",82640563,Medium,Medium,High Revenue,Hyper Growth,Top 100,West,High Efficiency
2,25643,3,145,Reliant Asset Management,Virginia,VA,Arlington,Washington DC,"55,460.16",85076502,Business Products & Services,1,"586,734.50",85076502,Medium,Medium,High Revenue,Hyper Growth,Top 100,South,Excellent Efficiency
3,26098,4,62,Superfish,California,CA,Palo Alto,San Jose,"26,042.96",35293000,Software,1,"569,241.94",35293000,Medium,Small,Medium Revenue,Hyper Growth,Top 100,West,Excellent Efficiency
4,26182,5,92,Acacia Communications,Massachusetts,MA,Maynard,Boston,"20,690.46",77652360,Telecommunications,1,"844,047.39",77652360,Medium,Small,High Revenue,Hyper Growth,Top 100,Northeast,Excellent Efficiency

In [5]:
df.tail()

,id,rank,employee_count,company,state_name,state_code,city,metro,growth_percentage,revenue_usd,industry,years_on_list,revenue_per_employee,Revenue_in_million,company_size,employee_size_band,revenue_category,growth_category,rank_group,state region,efficiency_category
4995,3645,4996,32,Euclid Technology,Maryland,MD,Bethesda,Washington DC,42.55,4411889,Software,4,"137,871.53",4411889,Small,Small,Small Revenue,Moderate Growth,Remaining,South,Average Efficiency
4996,21959,4997,69,World Water Works,Oklahoma,OK,Oklahoma City,Oklahoma City OK,42.54,15039730,Environmental Services,3,"217,967.10",15039730,Medium,Small,Medium Revenue,Moderate Growth,Remaining,South,Average Efficiency
4997,367,4998,35,Sensis,California,CA,Los Angeles,Los Angeles,42.52,11078000,Advertising & Marketing,7,"316,514.29",11078000,Small,Small,Medium Revenue,Moderate Growth,Remaining,West,High Efficiency
4998,26459,4999,154,WBC Group,Ohio,OH,Hudson,Akron OH,42.51,67867115,Health,1,"440,695.55",67867115,Medium,Medium,High Revenue,Moderate Growth,Remaining,Midwest,High Efficiency
4999,24415,5000,230,Mach1 Global Services,Arizona,AZ,Tempe,Phoenix,42.45,105299201,Logistics & Transportation,3,"457,822.61",105299201,Medium,Medium,Very High Revenue,Moderate Growth,Remaining,West,High Efficiency

## Dataset Dimensions

In [6]:
rows, cols = df.shape

print(f"Rows    : {rows:,}")
print(f"Columns : {cols}")

Rows    : 5,000
Columns : 21

## Column Names

In [7]:
for i, column in enumerate(df.columns, start=1):
    print(f"{i:02d}. {column}")

01. id
02. rank
03. employee_count
04. company
05. state_name
06. state_code
07. city
08. metro
09. growth_percentage
10. revenue_usd
11. industry
12. years_on_list
13. revenue_per_employee
14. Revenue_in_million
15. company_size
16. employee_size_band
17. revenue_category
18. growth_category
19. rank_group
20. state region
21. efficiency_category

## Data Types

In [8]:
df.dtypes

id                     int64
rank                   int64
employee_count         int64
company                  str
state_name               str
                       ...
revenue_category         str
growth_category          str
rank_group               str
state region             str
efficiency_category      str
Length: 21, dtype: object

In [9]:
df.info

<bound method DataFrame.info of          id  rank  employee_count                   company     state_name  \
0     22890     1             227                      Fuhu     California
1     25747     2             191           Quest Nutrition     California
2     25643     3             145  Reliant Asset Management       Virginia
3     26098     4              62                 Superfish     California
4     26182     5              92     Acacia Communications  Massachusetts
...     ...   ...             ...                       ...            ...
4995   3645  4996              32         Euclid Technology       Maryland
4996  21959  4997              69         World Water Works       Oklahoma
4997    367  4998              35                    Sensis     California
4998  26459  4999             154                 WBC Group           Ohio
4999  24415  5000             230     Mach1 Global Services        Arizona

     state_code           city             metro  growth_percentage  \
0            CA     El Segundo       Los Angeles         158,956.91
1            CA     El Segundo       Los Angeles          57,347.92
2            VA      Arlington     Washington DC          55,460.16
3            CA      Palo Alto          San Jose          26,042.96
4            MA        Maynard            Boston          20,690.46
...         ...            ...               ...                ...
4995         MD       Bethesda     Washington DC              42.55
4996         OK  Oklahoma City  Oklahoma City OK              42.54
4997         CA    Los Angeles       Los Angeles              42.52
4998         OH         Hudson          Akron OH              42.51
4999         AZ          Tempe           Phoenix              42.45

      revenue_usd                      industry  years_on_list  \
0       195640000  Consumer Products & Services              2
1        82640563               Food & Beverage              1
2        85076502  Business Products & Services              1
3        35293000                      Software              1
4        77652360            Telecommunications              1
...           ...                           ...            ...
4995      4411889                      Software              4
4996     15039730        Environmental Services              3
4997     11078000       Advertising & Marketing              7
4998     67867115                        Health              1
4999    105299201    Logistics & Transportation              3

     revenue_per_employee  Revenue_in_million company_size employee_size_band  \
0              861,850.22           195640000       Medium             Medium
1              432,673.10            82640563       Medium             Medium
2              586,734.50            85076502       Medium             Medium
3              569,241.94            35293000       Medium              Small
4              844,047.39            77652360       Medium              Small
...                   ...                 ...          ...                ...
4995           137,871.53             4411889        Small              Small
4996           217,967.10            15039730       Medium              Small
4997           316,514.29            11078000        Small              Small
4998           440,695.55            67867115       Medium             Medium
4999           457,822.61           105299201       Medium             Medium

       revenue_category  growth_category rank_group state region  \
0     Very High Revenue     Hyper Growth    Top 100         West
1          High Revenue     Hyper Growth    Top 100         West
2          High Revenue     Hyper Growth    Top 100        South
3        Medium Revenue     Hyper Growth    Top 100         West
4          High Revenue     Hyper Growth    Top 100    Northeast
...                 ...              ...        ...          ...
4995      Small Revenue  Moderate Growth  Remaining        South
4996     Medium Revenue  Moderate Growth  Remaining        South
4997     Medium Revenue  Moderate Growth  Remaining         West
4998       High Revenue  Moderate Growth  Remaining      Midwest
4999  Very High Revenue  Moderate Growth  Remaining         West

       efficiency_category
0     Excellent Efficiency
1          High Efficiency
2     Excellent Efficiency
3     Excellent Efficiency
4     Excellent Efficiency
...                    ...
4995    Average Efficiency
4996    Average Efficiency
4997       High Efficiency
4998       High Efficiency
4999       High Efficiency

[5000 rows x 21 columns]>

## Dataset Overview

In [10]:
overview = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Non-Null Count": df.count().values,
    "Missing Values": df.isna().sum().values,
    "Unique Values": df.nunique().values
})

overview

,Column,Data Type,Non-Null Count,Missing Values,Unique Values
0,id,int64,5000,0,5000
1,rank,int64,5000,0,5000
2,employee_count,int64,5000,0,657
3,company,str,5000,0,5000
4,state_name,str,5000,0,51
...,...,...,...,...,...
16,revenue_category,str,5000,0,5
17,growth_category,str,5000,0,4
18,rank_group,str,5000,0,5
19,state region,str,5000,0,5
20,efficiency_category,str,5000,0,5

## Numerical Columns

In [11]:
numerical_columns = df.select_dtypes(include="number").columns

print(f"Total Numerical Columns: {len(numerical_columns)}")
print()

for col in numerical_columns:
    print(col)

Total Numerical Columns: 7

id
rank
employee_count
growth_percentage
revenue_usd
years_on_list
Revenue_in_million

## Categorical Columns

In [13]:
categorical_columns = df.select_dtypes(include=["object", "category"]).columns

print(f"Total Categorical Columns: {len(categorical_columns)}")
print()

for col in categorical_columns:
    print(col)

Total Categorical Columns: 14

company
state_name
state_code
city
metro
industry
revenue_per_employee
company_size
employee_size_band
revenue_category
growth_category
rank_group
state region
efficiency_category

C:\Users\dell\AppData\Local\Temp\ipykernel_21436\4138092923.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object", "category"]).columns

## Date Columns

In [12]:
date_columns = df.select_dtypes(include=["datetime64[ns]"]).columns

if len(date_columns) == 0:
    print("No datetime columns detected.")
else:
    print(date_columns)

No datetime columns detected.

## First Five Records

In [14]:
df.sample(5, random_state=42)

,id,rank,employee_count,company,state_name,state_code,city,metro,growth_percentage,revenue_usd,industry,years_on_list,revenue_per_employee,Revenue_in_million,company_size,employee_size_band,revenue_category,growth_category,rank_group,state region,efficiency_category
1501,23258,1502,1299,Stratosphere Quality,Indiana,IN,Fishers,Indianapolis IN,285.55,80646568,Manufacturing,2,"62,083.58",80646568,Enterprise,Very Large,High Revenue,High Growth,Top 2500,Midwest,Low Efficiency
2586,22309,2587,2700,LEGACY Supply Chain Services,New Hampshire,NH,Portsmouth,Boston,145.21,343314075,Logistics & Transportation,8,"127,153.36",343314075,Enterprise,Very Large,Very High Revenue,High Growth,Remaining,Northeast,Average Efficiency
2653,24286,2654,29,IMPRES Technology Solutions,California,CA,Santa Fe Springs,Los Angeles,141.31,36963967,Government Services,2,"1,274,619.55",36963967,Small,Small,Medium Revenue,High Growth,Remaining,West,Excellent Efficiency
1055,22578,1056,40,Inilex,Arizona,AZ,Phoenix,Phoenix,421.91,16690369,Security,3,"417,259.22",16690369,Small,Small,Medium Revenue,High Growth,Top 2500,West,High Efficiency
705,25714,706,12,NovelASPect.com,California,CA,San Mateo,San Francisco,641.78,2439374,IT Services,1,"203,281.17",2439374,Small,Very Small,Small Revenue,Very High Growth,Top 1000,West,Average Efficiency

## Dataset Summary

In [15]:
summary = {
    "Rows": df.shape[0],
    "Columns": df.shape[1],
    "Numerical Columns": len(numerical_columns),
    "Categorical Columns": len(categorical_columns),
    "Missing Values": int(df.isna().sum().sum()),
    "Duplicate Rows": int(df.duplicated().sum())
}

summary_df = pd.DataFrame(summary.items(), columns=["Metric", "Value"])

summary_df

                Metric  Value
0                 Rows   5000
1              Columns     21
2    Numerical Columns      7
3  Categorical Columns     14
4       Missing Values     58
5       Duplicate Rows      0

## Key Takeaways

This notebook successfully:

- Loaded the cleaned Excel dataset
- Verified dataset dimensions
- Examined column names
- Reviewed data types
- Identified numerical and categorical features
- Measured memory usage
- Generated an initial dataset summary

The dataset is now ready for validation and quality assessment in the next notebook.

**Next Notebook:** `02_data_validation.ipynb`